app_pesanan/urls.py
from django.conf.urls import url
from django.urls import path
from .views import form_pemesanan, daftar_pemesanan, update_pemesanan


app_name = "app_pesanan"


urlpatterns = [
    path('', daftar_pemesanan, name='daftar_pemesanan'),
    path('pesan/', form_pemesanan, name='form_pemesanan'),
    path('update/', update_pemesanan, name='update_pemesanan'),
]

chat/urls.py
from django.urls import path
from .views import index, chatAdmin

app_name = 'chat'

urlpatterns = [
    path('', index, name='index'),
    path('admin', chatAdmin, name='chatAdmin')
]

toysrent/urls.py
from django.contrib import admin
from django.urls import path, include

import app_pengiriman.urls as app_pengiriman
import app_review.urls as app_review
import app_pesanan.urls as app_pesanan
import app_level.urls as app_level

urlpatterns = [
    path('admin/', admin.site.urls),
    path('barang/', include('barang.urls')),
    path('pengiriman/', include(app_pengiriman)),
    path('review/', include(app_review)),
    path('pemesanan/', include(app_pesanan)),
    path('level/', include(app_level)),
    path('chat/', include('chat.urls')),
    path('item/', include('item.urls')),
    path('auth/', include('app_auth.urls')),
    path('profil/', include('profil.urls')),
]

app_pesanan/models.py
from django.db import models

# Create your models here.

app_pesanan/views.py
from django.shortcuts import render
from django.db import connection

# Create your views here.

def daftar_pemesanan(request):
    response = {}
    with connection.cursor() as cursor:
        cursor.execute("SELECT id_pemesanan, (harga_sewa + ongkos), status FROM PEMESANAN")
        all_orders_record = cursor.fetchall()

        counter = 0
        for row in all_orders_record:
            cursor.execute("SELECT b.nama_item from barang as b, barang_pesanan as d, pemesanan as p where b.id_barang = d.id_barang AND d.id_pemesanan = p.id_pemesanan AND p.id_pemesanan = \'{}\'".format(row[0]))
            order_item_record = cursor.fetchall() # a list of tuples of single string (what a waste!)
            order_items_tuple = tuple() # oh no I forget to implement clean code
            for item in order_item_record:
                order_items_tuple += item # take the only element from each tuple and add to a new tuple
            all_orders_record[counter] += (order_items_tuple,)
            counter += 1
    response['daftar_pemesanan'] = all_orders_record
    return render(request, 'daftar-pemesanan.html', response)

def form_pemesanan(request):
    response = {}
    return render(request, 'form-pemesanan.html', response)

def update_pemesanan(request):
    response = {}
    return render(request, 'update-pemesanan.html', response)

app_pesanan/templates/daftar-pemesanan.html
{% load static %}

<!DOCTYPE html>
<html lang="id">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- For Bootstrap -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js" integrity="sha384-ZMP7rVo3mIykV+2+9J3UJ46jBk0WLaUAdn689aCwoqbBJiSnjAK/l8WvCWPIPm49" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/js/bootstrap.min.js" integrity="sha384-ChfqqxuZUCnJSK3+MXmPNIyE6ZbWh2IMqE241rYiqJxyMiZ6OW/JmZQ5stwEULTy" crossorigin="anonymous"></script>
    <script src="//netdna.bootstrapcdn.com/bootstrap/3.1.1/js/bootstrap.min.js"></script>
    
    <title>ToysRent - Daftar Pemesanan</title>
</head>

<body>
    {% include 'navbar.html' %}

    <div class="container bg-light my-3">
        <div class="dropdown d-flex justify-content-end my-3">
            <button
            class="btn btn-primary dropdown-toggle"
            type="button"
            data-toggle="dropdown"
            id="dropdownMenuButton"
            data-toggle="dropdown"
            aria-haspopup="true"
            aria-expanded="false">Filter</button>

            <div class="dropdown-menu" aria-labelledby="dropdownMenuButton">
                <a class="dropdown-item" href="#">ID Pemesanan</a>
                <a class="dropdown-item" href="#">Harga Total - Asc</a>
                <a class="dropdown-item" href="#">Harga Total - Desc</a>
                <a class="dropdown-item" href="#">Status - Asc</a>
                <a class="dropdown-item" href="#">Status - Desc</a>
            </div>
        </div>
    
        <table class="table table-striped">
            <thead>
                <tr class="bg-primary text-light">
                <th scope="col">ID Pemesanan</th>
                <th scope="col">Daftar Barang</th>
                <th scope="col">Harga</th>
                <th scope="col">Status</th>
                <th scope="col">Action</th>
                </tr>
            </thead>
            <tbody>
                {% for tuple in daftar_pemesanan %}
                <tr>
                    <form>
                    <th scope="row">{{ tuple.0 }}</th>
                    <td>
                        {% for item in tuple.3 %}
                        <li>{{item}}</li>
                        {% endfor %}
                    </td>
                    <td>{{tuple.1}}</td>
                    <td>{{tuple.2}}</td>
                    <td>
                        <a type="button" class="btn btn-primary" href="{% url 'app_pesanan:update_pemesanan' %}">Update</a>
                        <button type="button" class="btn btn-danger">Delete</button>
                    </td>
                    </form>
                </tr>
                {% endfor %}

            </tbody>
        </table>
    
        <nav aria-label="Pengiriman page navigation">
            <ul class="pagination">
                <li class="page-item">
                    <a class="page-link" href="#" aria-label="Previous">
                        <span aria-hidden="true">&laquo;</span>
                        <span class="sr-only">Previous</span>
                    </a>
                </li>
                <li class="page-item active"><a class="page-link" href="#">1</a></li>
                <li class="page-item"><a class="page-link" href="#">2</a></li>
                <li class="page-item"><a class="page-link" href="#">3</a></li>
                <li class="page-item">
                    <a class="page-link" href="#" aria-label="Next">
                        <span aria-hidden="true">&raquo;</span>
                        <span class="sr-only">Next</span>
                    </a>
                </li>
            </ul>
        </nav>
    </div>
</body>
</html>

app_pesanan/templates/form-pemesanan.html
{% load static %}

<!DOCTYPE html>
<html lang="id">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- For Bootstrap -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js" integrity="sha384-ZMP7rVo3mIykV+2+9J3UJ46jBk0WLaUAdn689aCwoqbBJiSnjAK/l8WvCWPIPm49" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/js/bootstrap.min.js" integrity="sha384-ChfqqxuZUCnJSK3+MXmPNIyE6ZbWh2IMqE241rYiqJxyMiZ6OW/JmZQ5stwEULTy" crossorigin="anonymous"></script>
    <script src="//netdna.bootstrapcdn.com/bootstrap/3.1.1/js/bootstrap.min.js"></script>
    
    <title>ToysRent - Form Pemesanan</title>
</head>

<body>
    {% include 'navbar.html' %}

    <div class="container bg-light my-3 d-flex justify-content-center">
        <form class="py-3 col-md-6 ">
            <h1 class="text-center" style="font-size:20pt">
                Form Pembuatan Pengiriman
            </h1>

            <div class="form-group">
                <label for="anggota">Anggota</label>
                <select class="form-control" id="anggota">
                    <option>Anggota 1</option>
                    <option>Anggota 2</option>
                    <option>Anggota 3</option>
                    <option>Anggota 4</option>
                </select>
            </div>

            <div class="form-group">
                <label for="barangPesanan">Barang Pesanan</label>
                <select multiple class="form-control" id="barangPesanan">
                    <option>Barang 1</option>
                    <option>Barang 2</option>
                    <option>Barang 3</option>
                    <option>Barang 4</option>
                </select>
            </div>

            <div class="form-group">
                <label for="lamaSewa">Lama Sewa</label>
                <input type="number" class="form-control" id="lamaSewa">
            </div>

            <button type="submit" class="btn btn-primary">Submit</button>
        </form>
    </div>
</body>
</html>

app_pesanan/templates/update-pemesanan.html
{% load static %}

<!DOCTYPE html>
<html lang="id">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- For Bootstrap -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js" integrity="sha384-ZMP7rVo3mIykV+2+9J3UJ46jBk0WLaUAdn689aCwoqbBJiSnjAK/l8WvCWPIPm49" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/js/bootstrap.min.js" integrity="sha384-ChfqqxuZUCnJSK3+MXmPNIyE6ZbWh2IMqE241rYiqJxyMiZ6OW/JmZQ5stwEULTy" crossorigin="anonymous"></script>
    <script src="//netdna.bootstrapcdn.com/bootstrap/3.1.1/js/bootstrap.min.js"></script>
    
    <title>ToysRent - Update Pemesanan</title>
</head>

<body>
    {% include 'navbar.html' %}

    <div class="container bg-light my-3 d-flex justify-content-center">
			<form class="py-3 col-md-6 ">
				<h1 class="text-center" style="font-size:20pt">
					Form Update Pengiriman
                </h1>

                <div class="form-group row">
                    <label for="namaBarang" class="col-sm-2 col-form-label">Nama Barang</label>
                    <div class="col-sm-10">
                        <input type="text" readonly class="form-control-plaintext" id="namaBarang" value="Barang 1 Merk A Warna Merah, Barang 2 Merk B Warna Biru">
                    </div>
                </div>
                
                <div class="form-group">
                    <label for="lamaSewa">Lama Sewa</label>
                    <input type="number" class="form-control" id="lamaSewa">
                </div>

                <div class="form-group">
                    <label for="status">Status</label>
                    <select class="form-control" id="status">
                        <option>Sedang dikonfirmasi</option>
                        <option>Sedang disiapkan</option>
                        <option>Sedang dikirim</option>
                        <option>Dalam masa sewa</option>
                        <option>Sudah dikembalikan</option>
                        <option>Batal</option>
                    </select>
                </div>

				<button type="submit" class="btn btn-primary">Update</button>
			</form>
		</div>
</body>
</html>