app_level/urls.py
from django.conf.urls import url
from django.urls import path
from .views import tambah_level, daftar_level, update_level


app_name = "app_level"


urlpatterns = [
    path('', daftar_level, name='daftar_level'),
    path('tambah-level/', tambah_level, name='tambah_level'),
    path('update-level/', update_level, name='update_level'),
]

app_pesanan/urls.py
from django.conf.urls import url
from django.urls import path
from .views import form_pemesanan, daftar_pemesanan, update_pemesanan


app_name = "app_pesanan"


urlpatterns = [
    path('', daftar_pemesanan, name='daftar_pemesanan'),
    path('pesan/', form_pemesanan, name='form_pemesanan'),
    path('update/', update_pemesanan, name='update_pemesanan'),
]

app_review/urls.py
from django.conf.urls import url
from django.urls import include
from .views import index, form_create_review, form_update_review

app_name = 'app_review'

urlpatterns = [
    url(r'^$', index, name='list_review'),
    url(r'form-create/$', form_create_review, name='form_create_review'),
    url(r'form-update/$', form_update_review, name='form_update_review'),
]

barang/urls.py
from django.urls import path
from .views import index, detail, update, create, delete

app_name = 'barang'

urlpatterns = [
    path('', index, name='index'),
    path('detail/<str:id>', detail, name='detail'),
    path('update/<str:id>', update, name='update'),
    path('delete/<str:id>', delete, name='delete'),
    path('create', create, name='create')
]

chat/urls.py
from django.urls import path
from .views import index, chatAdmin

app_name = 'chat'

urlpatterns = [
    path('', index, name='index'),
    path('admin', chatAdmin, name='chatAdmin')
]

toysrent/urls.py
from django.contrib import admin
from django.urls import path, include

import app_pengiriman.urls as app_pengiriman
import app_review.urls as app_review
import app_pesanan.urls as app_pesanan
import app_level.urls as app_level

urlpatterns = [
    path('admin/', admin.site.urls),
    path('barang/', include('barang.urls')),
    path('pengiriman/', include(app_pengiriman)),
    path('review/', include(app_review)),
    path('pemesanan/', include(app_pesanan)),
    path('level/', include(app_level)),
    path('chat/', include('chat.urls')),
    path('item/', include('item.urls')),
    path('auth/', include('app_auth.urls')),
    path('profil/', include('profil.urls')),
]

templates/navbar.html
<nav class="navbar navbar-expand-lg navbar-dark bg-primary">
    <a class="navbar-brand" href="#">[ ToysRent ]</a>
    <button
        class="navbar-toggler"
        type="button"
        data-toggle="collapse"
        data-target="#navbarNavDropdown"
        aria-controls="navbarNavDropdown"
        aria-expanded="false"
        aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse" id="navbarNavDropdown">
        <ul class="navbar-nav">
            <li class="nav-item active">
                <a class="nav-link" href="#">Home <span class="sr-only">(current)</span></a>
                </li>
            <li class="nav-item">
                <a class="nav-link" href="/auth/login">Login</a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="/auth/signup">Signup</a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="/auth/item">Item</a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="{% url 'barang:index' %}">Barang</a>
            </li>
            <li class="nav-item dropdown">
                <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                    Pemesanan
                </a>
                <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                    <a class="dropdown-item" href="{% url 'app_pesanan:daftar_pemesanan' %}">Daftar Pemesanan</a>
                    <a class="dropdown-item" href="{% url 'app_pesanan:form_pemesanan' %}">Form Pemesanan</a>
                </div>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="{% url 'app_pengiriman:list_pengiriman' %}">Pengiriman</a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="{% url 'app_review:list_review' %}">Review</a>
            </li>
            <li class="nav-item dropdown">
                <a class="nav-link dropdown-toggle" href="#" id="navbarDropdownLevel" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                    Level
                </a>
                <div class="dropdown-menu" aria-labelledby="navbarDropdownLevel">
                    <a class="dropdown-item" href="{% url 'app_level:daftar_level' %}">Daftar Level</a>
                    <a class="dropdown-item" href="{% url 'app_level:tambah_level' %}">Tambah Level</a>
                </div>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="#">Profil</a>
            </li>
        </ul>
    </div>
</nav>
      