app_level/urls.py
from django.conf.urls import url
from django.urls import path
from .views import tambah_level, daftar_level, update_level


app_name = "app_level"


urlpatterns = [
    path('', daftar_level, name='daftar_level'),
    path('tambah-level/', tambah_level, name='tambah_level'),
    path('update-level/', update_level, name='update_level'),
]

chat/urls.py
from django.urls import path
from .views import index, chatAdmin

app_name = 'chat'

urlpatterns = [
    path('', index, name='index'),
    path('admin', chatAdmin, name='chatAdmin')
]

toysrent/urls.py
from django.contrib import admin
from django.urls import path, include

import app_pengiriman.urls as app_pengiriman
import app_review.urls as app_review
import app_pesanan.urls as app_pesanan
import app_level.urls as app_level

urlpatterns = [
    path('admin/', admin.site.urls),
    path('barang/', include('barang.urls')),
    path('pengiriman/', include(app_pengiriman)),
    path('review/', include(app_review)),
    path('pemesanan/', include(app_pesanan)),
    path('level/', include(app_level)),
    path('chat/', include('chat.urls')),
    path('item/', include('item.urls')),
    path('auth/', include('app_auth.urls')),
    path('profil/', include('profil.urls')),
]

app_level/models.py
from django.db import models

# Create your models here.

app_level/views.py
from django.shortcuts import render
from django.db import connection

# Create your views here.

def daftar_level(request):
    response = {}
    with connection.cursor() as cursor:
        cursor.execute("SELECT nama_level, deskripsi, minimum_poin FROM LEVEL_KEANGGOTAAN")
        all_levels = cursor.fetchall()

        counter = 1
        for row in all_levels:
            row += (counter,)
            counter += 1
    response['daftar_level'] = all_levels
    return render(request, 'daftar-level.html', response)

def tambah_level(request):
    response = {}
    return render(request, 'tambah-level.html', response)

def update_level(request):
    response = {}
    return render(request, 'update-level.html', response)

app_level/templates/daftar-level.html
{% load static %}

<!DOCTYPE html>
<html lang="id">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- For Bootstrap -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js" integrity="sha384-ZMP7rVo3mIykV+2+9J3UJ46jBk0WLaUAdn689aCwoqbBJiSnjAK/l8WvCWPIPm49" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/js/bootstrap.min.js" integrity="sha384-ChfqqxuZUCnJSK3+MXmPNIyE6ZbWh2IMqE241rYiqJxyMiZ6OW/JmZQ5stwEULTy" crossorigin="anonymous"></script>
    <script src="//netdna.bootstrapcdn.com/bootstrap/3.1.1/js/bootstrap.min.js"></script>
    
    <title>ToysRent - Daftar Level</title>
</head>

<body>
    {% include 'navbar.html' %}

    <div class="container bg-light my-3">
        <div class="dropdown d-flex justify-content-end my-3">
            <button
            class="btn btn-primary dropdown-toggle"
            type="button"
            data-toggle="dropdown"
            id="dropdownMenuButton"
            data-toggle="dropdown"
            aria-haspopup="true"
            aria-expanded="false">Filter</button>

            <div class="dropdown-menu" aria-labelledby="dropdownMenuButton">
                <a class="dropdown-item" href="#">No.</a>
                <a class="dropdown-item" href="#">Nama Level - Asc</a>
                <a class="dropdown-item" href="#">Nama Level - Desc</a>
                <a class="dropdown-item" href="#">Minimum Poin - Asc</a>
                <a class="dropdown-item" href="#">Minimum Poin - Desc</a>
            </div>
        </div>
    
        <table class="table table-striped">
            <thead>
                <tr class="bg-primary text-light">
                <th scope="col">No.</th>
                <th scope="col">Nama Level</th>
                <th scope="col">Deskripsi</th>
                <th scope="col">Minimum Poin</th>
                <th scope="col">Action</th>
                </tr>
            </thead>
            <tbody>
                {% for tuple in daftar_level %}
                <tr>
                    <th scope="row">{{tuple.3}}</th>
                    <td>{{tuple.0}}</td>
                    <td>{{tuple.1}}</td>
                    <td>{{tuple.2}}</td>
                    <td>
                        <a type="button" class="btn btn-primary" href="{% url 'app_level:update_level' %}">Update</a>
                        <button type="button" class="btn btn-danger">Delete</button>
                    </td>
                </tr>
                {% endfor %}
                
            </tbody>
        </table>
    
        <nav aria-label="Pengiriman page navigation">
            <ul class="pagination">
                <li class="page-item">
                    <a class="page-link" href="#" aria-label="Previous">
                        <span aria-hidden="true">&laquo;</span>
                        <span class="sr-only">Previous</span>
                    </a>
                </li>
                <li class="page-item active"><a class="page-link" href="#">1</a></li>
                <li class="page-item"><a class="page-link" href="#">2</a></li>
                <li class="page-item"><a class="page-link" href="#">3</a></li>
                <li class="page-item">
                    <a class="page-link" href="#" aria-label="Next">
                        <span aria-hidden="true">&raquo;</span>
                        <span class="sr-only">Next</span>
                    </a>
                </li>
            </ul>
        </nav>
    </div>
</body>
</html>

app_level/templates/tambah-level.html
{% load static %}

<!DOCTYPE html>
<html lang="id">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- For Bootstrap -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js" integrity="sha384-ZMP7rVo3mIykV+2+9J3UJ46jBk0WLaUAdn689aCwoqbBJiSnjAK/l8WvCWPIPm49" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/js/bootstrap.min.js" integrity="sha384-ChfqqxuZUCnJSK3+MXmPNIyE6ZbWh2IMqE241rYiqJxyMiZ6OW/JmZQ5stwEULTy" crossorigin="anonymous"></script>
    <script src="//netdna.bootstrapcdn.com/bootstrap/3.1.1/js/bootstrap.min.js"></script>
    
    <title>ToysRent - Tambah Level</title>
</head>

<body>
    {% include 'navbar.html' %}

    <div class="container bg-light my-3 d-flex justify-content-center">
        <form class="py-3 col-md-6 ">
            <h1 class="text-center" style="font-size:20pt">
                Tambahkan Level
            </h1>

            <div class="form-group">
                <label for="namaLevel">Nama level</label>
                <input type="text" class="form-control" id="namaLevel">
            </div>

            <div class="form-group">
                <label for="minimumPoin">Minimum poin</label>
                <input type="number" class="form-control" id="minimumPoin">
            </div>

            <div class="form-group">
                <label for="deskripsi">Deskripsi</label>
                <input type="text" class="form-control" id="deskripsi">
            </div>

            <button type="submit" class="btn btn-primary">Submit</button>
        </form>
    </div>
</body>
</html>

app_level/templates/update-level.html
{% load static %}

<!DOCTYPE html>
<html lang="id">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- For Bootstrap -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js" integrity="sha384-ZMP7rVo3mIykV+2+9J3UJ46jBk0WLaUAdn689aCwoqbBJiSnjAK/l8WvCWPIPm49" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/js/bootstrap.min.js" integrity="sha384-ChfqqxuZUCnJSK3+MXmPNIyE6ZbWh2IMqE241rYiqJxyMiZ6OW/JmZQ5stwEULTy" crossorigin="anonymous"></script>
    <script src="//netdna.bootstrapcdn.com/bootstrap/3.1.1/js/bootstrap.min.js"></script>
    
    <title>ToysRent - Update Level</title>
</head>

<body>
    {% include 'navbar.html' %}

    <div class="container bg-light my-3 d-flex justify-content-center">
			<form class="py-3 col-md-6 ">
                    <h1 class="text-center" style="font-size:20pt">
                        Update Level
                    </h1>
        
                    <div class="form-group">
                        <label for="namaLevel">Nama level</label>
                        <input type="text" class="form-control" id="namaLevel" value="GOLD">
                    </div>
        
                    <div class="form-group">
                        <label for="minimumPoin">Minimum poin</label>
                        <input type="number" class="form-control" id="minimumPoin" value="100">
                    </div>
        
                    <div class="form-group">
                        <label for="deskripsi">Deskripsi</label>
                        <input type="text" class="form-control" id="deskripsi" value="Level Menengah Atas">
                    </div>

				<button type="submit" class="btn btn-primary">Update</button>
			</form>
		</div>
</body>
</html>